version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: orchestrator-db
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
      POSTGRES_DB: orchestrator_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: orchestrator-auth
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql+asyncpg://orchestrator:orchestrator@postgres:5432/orchestrator_db
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: orchestrator-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
    environment:
      - JWT_SECRET=supersecretkey_orchestrator
      - AUTH_URL=http://auth:8081/auth

  vm-placement:
    build: ./vm-placement
    container_name: vm-placement
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=postgresql+asyncpg://orchestrator:orchestrator@postgres:5432/orchestrator_db
    depends_on:
      - postgres
  
  image-manager:
    build:
      context: ./image-manager
      dockerfile: Dockerfile
    container_name: orchestrator-image-manager
    ports:
      - "8083:8083"
    environment:
      - IMAGE_BASE_PATH=/mnt/storage/base/
      - IMAGE_INSTANCES_PATH=/mnt/storage/instances/
    volumes:
      - /mnt/storage:/mnt/storage

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: orchestrator-monitoring
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgresql+asyncpg://orchestrator:orchestrator@postgres:5432/orchestrator_db
      - SSH_ENABLED=true
    depends_on:
      - postgres
    volumes:
      - ~/.ssh:/root/.ssh:ro

volumes:
  pgdata:
